[package]
name = "fox32"
version = "0.1.0"
authors = ["ry"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
pixels = "0.9.0"
rodio = "0.14.0"
winit = "0.26"
winit_input_helper = "0.11"
