on:
  push:
    branches:
      - main
    paths:
      - 'fox32asm/**'

name: fox32asm Unstable - Windows

jobs:
  fox32asm-unstable-windows:
    name: Build
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./fox32asm
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: fox32asm
          path: fox32asm/target/release/fox32asm