on:
  push:
    branches:
      - main
    paths:
      - 'fox32/**'

name: fox32 Unstable - Windows

jobs:
  fox32-unstable-windows:
    name: Build
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./fox32
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: fox32.exe
          path: fox32/target/release/fox32.exe