on:
  push:
    branches:
      - main
    paths:
      - 'fox32rom/**'

name: fox32rom Unstable

jobs:
  fox32rom-unstable-linux:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fox32rom
    steps:
      - uses: actions/checkout@v2

      - name: Download latest fox32asm artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: fox32asm-unstable-linux.yml
          workflow_conclusion: success

      - name: Build
        run: |
          chmod +x ../fox32asm/fox32asm
          ../fox32asm/fox32asm main.asm fox32.rom

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: fox32.rom
          path: fox32rom/fox32.rom